name: Deploy to Firebase

on:
  workflow_dispatch: # allow manual runs
  push:
    branches:
      - main  # auto-deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with service account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${HOME}/sa.json"

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/sa.json"
        run: firebase deploy --only functions,firestore:rules,firestore:indexes --project georeminders-dcef9
